# Generated by Django 2.1.2 on 2018-11-04 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=200)),
                ('goal_id', models.IntegerField(default=0)),
                ('created_by', models.CharField(max_length=100)),
                ('moved_by', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nathmankindscrumy', to='nathmankindscrumy.GoalStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_by', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('moved_from', models.CharField(max_length=100)),
                ('moved_to', models.CharField(max_length=100)),
                ('time_of_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('scrumy_goals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='nathmankindscrumy.ScrumyGoals')),
            ],
        ),
    ]
